version: '3'
services:
  transaction:
    container_name: "transaction"
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongodb
      - auditserver
    #entrypoint: /bin/bash
    command: bash -c "go run *.go transaction"
    tty: true
  webserver:
    container_name: "webserver"
    build: .
    ports:
      - 8080:8080
    depends_on:
      - transaction
      - auditserver
    tty: true
    #entrypoint: /bin/bash
    command: bash -c "go run *.go webserver"
  auditserver:
    container_name: "auditserver"
    build: .
    ports:
      - 8081:8081
    command: bash -c "go run *.go auditserver"
    tty: true
    #entrypoint: /bin/bash
  workloadgen:
    container_name: "workloadgen"
    build: .
    tty: true
    entrypoint: /bin/bash
    depends_on:
      - webserver
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
