version: '3'
services:
  transaction:
    image: 192.168.1.150:5111/ability:latest
    container_name: "transaction"
    build:
      context: .
      dockerfile: Dockerfile
    #links:
    #  - mongo #:db1.prod.ability.com
    #  - audit #:auditserver.prod.ability.com
    #ports:
    #  - "44421"
    #expose:
    #  - 44421
    depends_on:
      - mongo
      - audit
    extra_hosts:
      - "quoteserve.seng:192.168.1.135"
    command: transaction --prod
    tty: true
    networks:
      mynetwork:
        aliases:
          - transactionserver
  web:
    container_name: "web"
    image: 192.168.1.150:5111/ability:latest
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  #- 44420
    #  - "8080:44420"
    #expose:
    #  - 44420
    #links:
    #  - transaction #:transaction.prod.ability.com
    #  - mongo #:db1.prod.ability.com
    #  - audit
    depends_on:
      - transaction
      - audit
    tty: true
    command: webserver --prod
    networks:
      mynetwork:
        aliases:
          - webserver
  audit:
    container_name: "auditserver"
    image: 192.168.1.150:5111/ability:latest
    build:
      context: .
      dockerfile: Dockerfile
    #expose:
    #  - 44422
    #ports:
    #  - "44422"
    command: auditserver --prod
    #links:
    #  - mongo #:db1.prod.ability.com
    tty: true
    networks:
      mynetwork:
        aliases:
          - auditserver
  workload:
    container_name: "workloadgen"
    image: 192.168.1.150:5111/workloadgen:latest
    build:
      context: workloads
      dockerfile: Dockerfile
    tty: true
    entrypoint: go run workloadgenerator.go 45User_testWorkLoad.txt
    #links:
    #  - web
    depends_on:
      - web
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      mynetwork:
        aliases:
          - workloadgen
  mongo:
    image: 192.168.1.150:5111/mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      #- MONGO_LOG_DIR=/dev/null
    #expose:
    #  - 44423
    #ports:
    #  - "44423"
    command: mongod --smallfiles --port 44423 #--bind_ip mongodb #--logpath=/dev/null # --quiet
    networks:
      mynetwork:
        aliases:
          - mongodb
networks:
  mynetwork:
    external: true
    #scope: swarm
    #attachable: true
