version: '3'
services:
  transaction:
    image: ability:latest
    container_name: "transaction"
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongodb:db1.prod.ability.com
      - auditserver:auditserver.prod.ability.com
    expose:
      - 44421
    depends_on:
      - mongodb
      - auditserver
    command: transaction --prod
    tty: true
    networks:
      mynetwork:
        aliases:
          - transaction.prod.ability.com
  web:
    container_name: "web"
    image: ability:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      #- 44420
      - "8080:44420"
    expose:
      - 44420
    links:
      - transaction:transaction.prod.ability.com
    depends_on:
      - transaction
      - auditserver
    tty: true
    command: webserver --prod
    networks:
      - scaryoutside
      - mynetwork
  auditserver:
    container_name: "auditserver"
    image: ability:latest
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 44422
    command: auditserver --prod
    tty: true
    networks:
      mynetwork:
        aliases:
          - auditserver.prod.ability.com
  workloadgen:
    container_name: "workloadgen"
    image: workloadgen:latest
    build:
      context: workloads
      dockerfile: Dockerfile
    tty: true
    #command: 1userWorkLoad.txt 1
    links:
      - web
    depends_on:
      - web
    networks:
      mynetwork:
        aliases:
          - workgen.prod.ability.com
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      #- MONGO_LOG_DIR=/dev/null
    expose:
      - 44423
    command: mongod --smallfiles --port 44423 --bind_ip db1.prod.ability.com #--logpath=/dev/null # --quiet
    networks:
      mynetwork:
        aliases:
          - db1.prod.ability.com
networks:
  mynetwork:
    driver: overlay
  scaryoutside:
