version: '3'
services:
  transaction:
    image: ability:latest
    container_name: "transaction"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 44421:44421
    depends_on:
      - mongodb
      - auditserver
    command: transaction --prod
    tty: true
    networks:
      mynetwork:
        aliases:
          - transaction.prod.ability.com
  webserver:
    container_name: "webserver"
    image: ability:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 44420:44420
    depends_on:
      - transaction
      - auditserver
    tty: true
    command: webserver --prod
    networks:
      mynetwork:
        aliases:
          - webserver.prod.ability.com
  auditserver:
    container_name: "auditserver"
    image: ability:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 44422:44422
    command: auditserver --prod
    tty: true
    networks:
      mynetwork:
        aliases:
          - auditserver.prod.ability.com
  workloadgen:
    container_name: "workloadgen"
    image: workloadgen:latest
    build:
      context: workloads
      dockerfile: Dockerfile
    tty: true
    #command: 1userWorkLoad.txt 1
    #entrypoint: /bin/bash
    depends_on:
      - webserver
    networks:
      mynetwork:
        aliases:
          - workgen.prod.ability.com
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      #- MONGO_LOG_DIR=/dev/null
    ports:
      - 44423:44423
    command: mongod --smallfiles --port 44423 --bind_ip db1.prod.ability.com #--logpath=/dev/null # --quiet
    networks:
      mynetwork:
        aliases:
          - db1.prod.ability.com
networks:
  mynetwork:
    driver: overlay
